services:
  - type: web
    name: line-sticker-bot
    runtime: docker
    envVars:
      - key: LINE_CHANNEL_SECRET
        sync: false
      - key: LINE_CHANNEL_ACCESS_TOKEN
        sync: false
      - key: BASE_URL
        sync: false
